// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mottu.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Mottu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515044104_AddSensorIoTMapping")]
    partial class AddSensorIoTMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM557481")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mottu.Models.Filial", b =>
                {
                    b.Property<int>("Id_Filial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Filial"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Filial");

                    b.ToTable("Filiais", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Log_Acao", b =>
                {
                    b.Property<int>("Id_Log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Log"));

                    b.Property<string>("Acao_Realizada")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id_Log");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Logs", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Moto", b =>
                {
                    b.Property<int>("Id_Moto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Moto"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Filial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Id_Sensor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status_Atual")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Moto");

                    b.HasIndex("Id_Filial");

                    b.HasIndex("Id_Sensor");

                    b.ToTable("Motos", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id_Mov")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Mov"));

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Id_Moto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Id_Operador")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Id_Vaga")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Saida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id_Mov");

                    b.HasIndex("Id_Moto");

                    b.HasIndex("Id_Operador");

                    b.HasIndex("Id_Vaga");

                    b.ToTable("Movimentacoes", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Operador", b =>
                {
                    b.Property<int>("Id_Operador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Operador"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Operador");

                    b.ToTable("Operadores", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Sensor_IoT", b =>
                {
                    b.Property<int>("Id_Sensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Sensor"));

                    b.Property<string>("Codigo_Tag")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Data_Ativacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id_Sensor");

                    b.ToTable("Sensor_IoT", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Status_Vaga", b =>
                {
                    b.Property<int>("Id_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Status"));

                    b.Property<string>("Descricao_Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Status");

                    b.ToTable("StatusVagas", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Usuario_Sistema", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha_Hash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("Usuarios", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Vaga_Estacionamento", b =>
                {
                    b.Property<int>("Id_Vaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Vaga"));

                    b.Property<int>("Id_Filial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Id_Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Numero_Vaga")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusDescricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id_Vaga");

                    b.HasIndex("Id_Filial");

                    b.HasIndex("Id_Status");

                    b.ToTable("VagasEstacionamento", "RM557481");
                });

            modelBuilder.Entity("Mottu.Models.Log_Acao", b =>
                {
                    b.HasOne("Mottu.Models.Usuario_Sistema", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mottu.Models.Moto", b =>
                {
                    b.HasOne("Mottu.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("Id_Filial")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mottu.Models.Sensor_IoT", "Sensor")
                        .WithMany()
                        .HasForeignKey("Id_Sensor");

                    b.Navigation("Filial");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Mottu.Models.Movimentacao", b =>
                {
                    b.HasOne("Mottu.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("Id_Moto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("Id_Operador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Models.Vaga_Estacionamento", "Vaga")
                        .WithMany()
                        .HasForeignKey("Id_Vaga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");

                    b.Navigation("Operador");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("Mottu.Models.Vaga_Estacionamento", b =>
                {
                    b.HasOne("Mottu.Models.Filial", "Filial_Referencia")
                        .WithMany()
                        .HasForeignKey("Id_Filial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mottu.Models.Status_Vaga", "Status")
                        .WithMany()
                        .HasForeignKey("Id_Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial_Referencia");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
